image:
  repository: jclblinux/nodeapp-counter
  tag: v2
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 30090

database:
  host: postgres-postgresql.nodeapp.svc.cluster.local
  port: 5432
  name: nodeapp
  user: nodeapp
  password: HesloNodeApp123

resources:
  limits:
    memory: 128Mi
    cpu: 200m
  requests:
    memory: 64Mi
    cpu: 50m