image:
  repository: jclblinux/nodeapp-counter
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

database:
  host: postgres-postgresql.nodeapp.svc.cluster.local
  port: 5432
  name: nodeapp
  user: nodeapp
  password: CHANGEME

resources:
  limits:
    memory: 128Mi
    cpu: 200m
  requests:
    memory: 64Mi
    cpu: 50m