---
- name: "stazeni helm scriptu"
  become: true
  ansible.builtin.shell:
    cmd: "curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash"
    creates: /usr/local/bin/helm
