---
- name: "Zkopirovani nodeapp values.yml z localu na EC2"
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../helm/nodeapp/values.yaml"
    dest: /home/ubuntu/nodeapp-values.yaml

- name: "Zkopirovani nodeapp Helm chartu z localu na EC2"
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../helm/nodeapp/"
    dest: /home/ubuntu/nodeapp-chart/
    mode: "0644"
    directory_mode: "0755"

- name: "Nasazeni nodeapp pres Helm"
  kubernetes.core.helm:
    release_name: nodeapp
    chart_ref: /home/ubuntu/nodeapp-chart/
    release_namespace: nodeapp
    create_namespace: true
    kubeconfig: /home/ubuntu/.kube/config
    values_files:
      - /home/ubuntu/nodeapp-values.yaml
    values:
      image:
        tag: "{{ nodeapp_image_tag }}"
      database:
        password: "{{ nodeapp_db_password }}"