prometheus:
  prometheusSpec:
    retention: 2d
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 512Mi
        cpu: 100m

grafana:
  adminPassword: GrafanaAdmin123
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: traefik
    path: /grafana
    pathType: Prefix
    hosts:
      - ""
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      serve_from_sub_path: true
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 200m

alertmanager:
  alertmanagerSpec:
    replicas: 1
    resources:
      limits:
        memory: 128Mi
        cpu: 100m
      requests:
        memory: 64Mi
        cpu: 10m

nodeExporter:
  resources:
    limits:
      memory: 64Mi
      cpu: 100m
    requests:
      memory: 32Mi
      cpu: 10m

kubeStateMetrics:
  resources:
    limits:
      memory: 128Mi
      cpu: 100m
    requests:
      memory: 64Mi
      cpu: 10m