auth:
  postgresPassword: changeMe
  username: nodeapp
  password: changeMe
  database: nodeapp

primary:
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 100m
  persistence:
    size: 4Gi
