auth:
  postgresPassword: HesloSA123
  username: nodeapp
  password: HesloNodeApp123
  database: nodeapp

primary:
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 100m
  persistence:
    size: 4Gi
